spring:
  profiles:
    active:
      - local, mybatis
    group:
      local:
        - db-local
        - db-local-jpa  # 또는 db-local-jpa
      dev:
        - db-dev
        - db-dev-jpa  # 또는 db-dev-jpa
    include:
      - db

springdoc:
  default-consumes-media-type: application/json # 소비 미디어 타입
  default-produces-media-type: application/json # 생산 미디어 타입
  swagger-ui:
    operations-sorter: method # operations 정렬 방식은 HTTP Method 순
    tags-sorter: alpha # tag 정렬 방식은 알파벳 순
    #path: "swagger.html" # http://localhost:8080/swagger.html로 접속 가능
    path: "/" # http://localhost:8080로 접속 가능
