#default 공통설정
#  jpa:
#    show-sql: true
#    properties:
#      jdbc:
#        time_zone: Asia/Seoul
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#sql:
#  init:
#    mode: always

mybatis:
  mapper-locations: classpath:/mappers/**.xml
  config-location: classpath:/config/mybatis-config.xml

logging:
  level:
    'org.springframework.jdbc': debug
    'org.store.clothstar': debug

jwt:
  secret_key: Y2xvdGhzaG9wcGluZ21hbGxjbG90aHN0YXJjbG90aHNob3BwaW5nbWFsbGNsb3Roc3RhcmNsb3Roc2hvcHBpbmdtYWxsY2xvdGhzdGFyY2xvdGhzaG9wcGluZ21hbGxjbG90aHN0YXIK
  accessTokenValidTimeMillis: 1200000
  refreshTokenValidTimeMillis: 12000000



--- # local 공통 설정
spring:
  config:
    activate:
      on-profile: "db-local"
  datasource:
    url: jdbc:h2:mem:localdb
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    database-platform: H2
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100


--- # dev 공통 설정
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  config:
    activate:
      on-profile: "db-dev"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(tdT8e3e+B4Lnbjjca9DuylTI2WMxolkaTxUyT4yJKbFLHUV0YynNjMss5AsaQJxEyndmGmgUlYTuJhx6667fcyUxGiV43314vgEwX+/NaVaSjIa2wiAmMfZu3WPVlgp/)
    username: ENC(xhLiaQAS5lcTT2hgCMRDOw==)
    password: ENC(XzhtQOZIlb9QjMX3klXi1EMBAuVOqWrM)
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
