env:
  S3_BUCKET_NAME: clothstar-bucket
  CODE_DEPLOY_APP_NAME: clothstar-deploy-v2
  DEPLOYMENT_GROUP_NAME: clothstar_deploy
  ZIP_FILE_NAME: clothstar-deploy.zip

name: aws-deploy
on:
  push:
    branches: develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Build with Gradle
        run: ./gradlew build
      - name: Make zip file
        run: zip -r ./$ZIP_FILE_NAME .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # 등록한 Github Secret이 자동으로 불려온다.
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # 등록한 Github Secret이 자동으로 불려온다.
          aws-region: ap-northeast-2
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$ZIP_FILE_NAME s3://$S3_BUCKET_NAME/$ZIP_FILE_NAME
      - name: Code Deploy
        run: >
          aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name $DEPLOYMENT_GROUP_NAME
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$ZIP_FILE_NAME
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          status: ${{ job.status }}
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}



